package Terceros;


/**
* Terceros/TerceroOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Terceros.idl
* miércoles 26 de septiembre de 2018 09:16:39 PM GMT-05:00
*/

public interface TerceroOperations 
{
  boolean insertarTercero (String nombres, String apellidos, String telefonos);
  boolean actualizarTercero (int id, String nombres, String apellidos, String telefonos);
  boolean eliminarTercero (int id);
  String consultarTercero (int id);
  void shoutdown ();
} // interface TerceroOperations
